services:
  orders:
    container_name: orders
    build:
      context: .
      target: development
      dockerfile: ./apps/order/Dockerfile
    command: pnpm start:dev order
    ports:
      - 3000:3000
    networks:
      - sharednet
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./apps/order/.env
      - .env
    environment:
      PG_HOST: host.docker.internal
    depends_on:
      - postgres
      - rabbitmq

  orders-collector:
    container_name: orders-collector
    build:
      context: .
      target: development
      dockerfile: ./apps/order-collector/Dockerfile
    command: pnpm start:dev order-collector
    networks:
      - sharednet
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./apps/order-collector/.env
    depends_on:
      - postgres
      - rabbitmq

  notifications:
    container_name: notifications
    build:
      context: .
      target: development
      dockerfile: ./apps/notification/Dockerfile
    command: pnpm start:dev notification
    ports:
      - 3001:3001
    networks:
      - sharednet
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./apps/notification/.env
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    container_name: shopify-postgres
    image: postgres:16.1
    networks:
      - sharednet
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq
    networks:
      - sharednet
    ports:
      - '5672:5672'

networks:
  sharednet:
volumes:
  pgdata:
